pipeline { 
    agent any
    stages { 
        stage('Build') { 
            steps { 
                script { 
                    echo 'Building...'
                    script {
                    bat 'mvn clean install' 
                    } 
                }
            } 
        } 
        stage('Test') {
            steps { 
                script { 
                    echo 'Testing...'
                    script { 
                        bat 'mvn test' 
                    } 
                    junit '**/target/surefire-reports/*.xml' 
                }
            }
        }
    }
    post { 
        always { 
            echo 'Cleaning up...' 
        } 
        success {
            echo 'Pipeline completed successfully!'
        } 
        failure { 
            echo 'Pipeline failed!' 
        }
    }       
        
